name: 'Build Images'

on:
  push:
    branches:
    - main
  pull_request: []

jobs:
  build:
    name: 'Build Images'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Read Version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.VERSION
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/${{ github.actor }}/ssp:${{ steps.version.outputs.content }}
          push: true
          labels: |-
            org.opencontainers.image.source=https://github.com/jim3ma/ssp